"""Add actual_eac_cents to project_forecasts

Revision ID: 12e59a1cfaf5
Revises: 20260116_phase1_seed
Create Date: 2026-01-16 15:32:29.454736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e59a1cfaf5'
down_revision: Union[str, Sequence[str], None] = '20260116_phase1_seed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip gmp_entities foreign key - already exists from previous migration

    with op.batch_alter_table('project_forecasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_eac_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_forecasts', schema=None) as batch_op:
        batch_op.drop_column('actual_eac_cents')

    # ### end Alembic commands ###
