"""Sync schema nullable and indexes

Revision ID: 7aea8e5648bf
Revises: 760ef25c116f
Create Date: 2026-01-13 06:49:47.634986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aea8e5648bf'
down_revision: Union[str, Sequence[str], None] = '760ef25c116f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_to_gmp', schema=None) as batch_op:
        batch_op.alter_column('side',
               existing_type=sa.VARCHAR(length=4),
               nullable=True,
               existing_server_default=sa.text("'BOTH'"))
        batch_op.drop_index(batch_op.f('ix_budget_to_gmp_division_side'))

    with op.batch_alter_table('direct_to_budget', schema=None) as batch_op:
        batch_op.alter_column('side',
               existing_type=sa.VARCHAR(length=4),
               nullable=True,
               existing_server_default=sa.text("'BOTH'"))
        batch_op.drop_index(batch_op.f('ix_direct_to_budget_budget_side'))

    with op.batch_alter_table('forecast_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_audit_log_changed_at'))

    with op.batch_alter_table('forecast_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_periods_granularity_division'))

    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_snapshots_division_current'))

    with op.batch_alter_table('schedule_activities', schema=None) as batch_op:
        batch_op.alter_column('start_is_actual',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('finish_is_actual',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_in_progress',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('progress_pct',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0.0'"))
        batch_op.alter_column('is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('mapping_source',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'manual'"))
        batch_op.alter_column('mapping_confidence',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'1.0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_activities', schema=None) as batch_op:
        batch_op.alter_column('mapping_confidence',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'1.0'"))
        batch_op.alter_column('mapping_source',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.alter_column('is_critical',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('progress_pct',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0.0'"))
        batch_op.alter_column('is_in_progress',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('finish_is_actual',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('start_is_actual',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_snapshots_division_current'), ['gmp_division', 'is_current'], unique=False)

    with op.batch_alter_table('forecast_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_periods_granularity_division'), ['granularity', 'gmp_division'], unique=False)

    with op.batch_alter_table('forecast_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_audit_log_changed_at'), ['changed_at'], unique=False)

    with op.batch_alter_table('direct_to_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_to_budget_budget_side'), ['budget_code', 'side'], unique=False)
        batch_op.alter_column('side',
               existing_type=sa.VARCHAR(length=4),
               nullable=False,
               existing_server_default=sa.text("'BOTH'"))

    with op.batch_alter_table('budget_to_gmp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_to_gmp_division_side'), ['gmp_division', 'side'], unique=False)
        batch_op.alter_column('side',
               existing_type=sa.VARCHAR(length=4),
               nullable=False,
               existing_server_default=sa.text("'BOTH'"))

    # ### end Alembic commands ###
